services:
  - type: web
    name: jobportal-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn jobportal.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: jobportal.settings
      - key: PYTHON_VERSION
        value: 3.11
      - key: SECRET_KEY
        value: your-secret-key
