services:
  - type: web
    name: jobportal-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn jobportal.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        value: your-secret-key
      - key: DATABASE_URL
        fromDatabase:
          name: jobportal-db
          property: connectionString