# Generated by Django 5.2.3 on 2025-06-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_recruiterprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiterprofile',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
